: MAIN MENU :

A:dd to BBS list   B:BS list           C:hat w/ sysop     D:efaults
F:eedback to sysop G:eneral files      H:write macros     I:nfo on system
L:og of the day    M:essage Menu       O:ff the system    T:ransfer system
U:ser list         V:ote               W:rite auto-msg    X:pert mode
Y:our info         $:change password   .:other programs   R:ead Bulletins
P:Gallery          N:Juke Box

