: WFC MENU :

 :Log On            A:Answer Phone      B:Board Edit        C:Drop to DOS
D:DL Board Edit     .:Edit Doors        F:dos routines      G:G-File Edit
I:Init Votes        L:Daily Log         M:Read Mail         P:Password Change
Q:Quit BBS          R:Read Feedback     S:Status            T:Terminal
V:Validate Users    Y:Yesterday's Log   Z:Zlog              =:Seclev Change
